version: "3"

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - ./:/code